#!/usr/bin/env bash
# Prepares Angular build output for embedding in ESP32 firmware.
# 1. Builds Angular app with esp32 config (or uses pre-built dist)
# 2. Copies to esp32/main/web/
# 3. Gzips text files
# 4. Generates web_files_gen.h (embedded file table) and web_embed.cmake (EMBED_FILES list)
#
# ESP-IDF EMBED_FILES generates symbols from the FILENAME only (not the path).
# e.g., web/icons/icon-512x512.png → _binary_icon_512x512_png_start
# All filenames must be unique across subdirectories.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
APP_DIR="$PROJECT_ROOT/app"
WEB_DIR="$PROJECT_ROOT/esp32/main/web"
DIST_DIR="$APP_DIR/dist/roku-remote/browser"
GEN_HEADER="$PROJECT_ROOT/esp32/main/web_files_gen.h"
GEN_CMAKE="$PROJECT_ROOT/esp32/web_embed.cmake"

# Step 1: Build Angular if dist doesn't exist or --build flag passed
if [[ "${1:-}" == "--build" ]] || [[ ! -d "$DIST_DIR" ]]; then
    echo "Building Angular app (esp32 configuration)..."
    (cd "$APP_DIR" && npx ng build --configuration esp32)
fi

# Step 2: Clean and copy
rm -rf "$WEB_DIR"
mkdir -p "$WEB_DIR"
cp -r "$DIST_DIR"/* "$WEB_DIR/"

# Remove service worker files (not needed for ESP32 HTTP serving)
rm -f "$WEB_DIR"/ngsw-worker.js "$WEB_DIR"/ngsw.json "$WEB_DIR"/safety-worker.js "$WEB_DIR"/worker-basic.min.js

echo "Web files copied to $WEB_DIR"

# Step 3: Gzip text files in place
TEXT_EXTENSIONS="html js css json webmanifest svg"
for ext in $TEXT_EXTENSIONS; do
    find "$WEB_DIR" -name "*.$ext" -exec gzip -9 -f {} \;
done

echo "Text files gzipped"

# Step 4: Generate the C header and CMake embed list

# ESP-IDF generates symbols from filename only: replace non-alnum with _
filename_to_symbol() {
    local filename
    filename=$(basename "$1")
    echo "$filename" | sed 's/[^a-zA-Z0-9]/_/g'
}

get_content_type() {
    case "$1" in
        *.html.gz) echo "text/html" ;;
        *.js.gz)   echo "application/javascript" ;;
        *.css.gz)  echo "text/css" ;;
        *.json.gz) echo "application/json" ;;
        *.webmanifest.gz) echo "application/manifest+json" ;;
        *.svg.gz)  echo "image/svg+xml" ;;
        *.png)     echo "image/png" ;;
        *.ico)     echo "image/x-icon" ;;
        *)         echo "application/octet-stream" ;;
    esac
}

# Verify all filenames are unique (ESP-IDF symbols are filename-based)
DUPES=$(find "$WEB_DIR" -type f -exec basename {} \; | sort | uniq -d)
if [[ -n "$DUPES" ]]; then
    echo "ERROR: Duplicate filenames found (ESP-IDF EMBED_FILES requires unique names):" >&2
    echo "$DUPES" >&2
    exit 1
fi

# Write the generated header
cat > "$GEN_HEADER" << 'HEADER_EOF'
#pragma once
// Auto-generated by prepare_web.sh — do not edit manually.
// ESP-IDF EMBED_FILES symbols are based on filename only (not path).

#include "web_files.h"

HEADER_EOF

# Add extern declarations
while IFS= read -r -d '' filepath; do
    symbol=$(filename_to_symbol "$filepath")
    cat >> "$GEN_HEADER" << DECL_EOF
extern const uint8_t ${symbol}_start[] asm("_binary_${symbol}_start");
extern const uint8_t ${symbol}_end[] asm("_binary_${symbol}_end");
DECL_EOF
done < <(find "$WEB_DIR" -type f -print0 | sort -z)

# Add the file count define and table
FILE_COUNT=$(find "$WEB_DIR" -type f | wc -l | tr -d ' ')

cat >> "$GEN_HEADER" << TABLE_START_EOF

#define WEB_FILE_COUNT ${FILE_COUNT}

static const WebFile web_files[] = {
TABLE_START_EOF

while IFS= read -r -d '' filepath; do
    relpath="${filepath#$WEB_DIR}"
    if [[ "$relpath" == *.gz ]]; then
        uri="${relpath%.gz}"
        gzipped="true"
    else
        uri="$relpath"
        gzipped="false"
    fi
    symbol=$(filename_to_symbol "$filepath")
    content_type=$(get_content_type "$relpath")

    echo "    { \"${uri}\", ${symbol}_start, static_cast<size_t>(${symbol}_end - ${symbol}_start), \"${content_type}\", ${gzipped} }," >> "$GEN_HEADER"
done < <(find "$WEB_DIR" -type f -print0 | sort -z)

cat >> "$GEN_HEADER" << 'TABLE_END_EOF'
};

static const int web_file_count = WEB_FILE_COUNT;
TABLE_END_EOF

echo "Generated $GEN_HEADER ($FILE_COUNT files)"

# Write CMake embed file — paths relative to main/ component directory
echo "# Auto-generated by prepare_web.sh — do not edit manually." > "$GEN_CMAKE"
echo "set(WEB_EMBED_FILES" >> "$GEN_CMAKE"
while IFS= read -r -d '' filepath; do
    relpath="${filepath#$WEB_DIR}"
    echo "    \"\${CMAKE_CURRENT_SOURCE_DIR}/web${relpath}\"" >> "$GEN_CMAKE"
done < <(find "$WEB_DIR" -type f -print0 | sort -z)
echo ")" >> "$GEN_CMAKE"

echo "Generated $GEN_CMAKE"
echo "Done! Run 'idf.py build' to compile firmware with embedded web files."
