#!/usr/bin/env bash
# Prepares Angular build output for embedding in ESP32 firmware.
# 1. Builds Angular app with esp32 config (or uses pre-built dist)
# 2. Copies to esp32/web/
# 3. Gzips text files
# 4. Generates web_files_gen.h (embedded file table) and web_embed.cmake (EMBED_FILES list)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
APP_DIR="$PROJECT_ROOT/app"
WEB_DIR="$PROJECT_ROOT/esp32/web"
DIST_DIR="$APP_DIR/dist/roku-remote/browser"
GEN_HEADER="$PROJECT_ROOT/esp32/main/web_files_gen.h"
GEN_CMAKE="$PROJECT_ROOT/esp32/web_embed.cmake"

# Step 1: Build Angular if dist doesn't exist or --build flag passed
if [[ "${1:-}" == "--build" ]] || [[ ! -d "$DIST_DIR" ]]; then
    echo "Building Angular app (esp32 configuration)..."
    (cd "$APP_DIR" && npx ng build --configuration esp32)
fi

# Step 2: Clean and copy
rm -rf "$WEB_DIR"
mkdir -p "$WEB_DIR"
cp -r "$DIST_DIR"/* "$WEB_DIR/"

# Remove service worker files (not needed for ESP32 HTTP serving)
rm -f "$WEB_DIR"/ngsw-worker.js "$WEB_DIR"/ngsw.json "$WEB_DIR"/safety-worker.js "$WEB_DIR"/worker-basic.min.js

echo "Web files copied to $WEB_DIR"

# Step 3: Gzip text files in place (keep originals for content-type detection)
TEXT_EXTENSIONS="html js css json webmanifest svg"
for ext in $TEXT_EXTENSIONS; do
    find "$WEB_DIR" -name "*.$ext" -exec gzip -9 -f {} \;
done

echo "Text files gzipped"

# Step 4: Generate the C header and CMake embed list
EMBED_FILES=""
ENTRIES=""
INDEX=0

generate_symbol() {
    # Convert filename to valid C symbol: replace non-alnum with _
    echo "$1" | sed 's/[^a-zA-Z0-9]/_/g'
}

get_content_type() {
    case "$1" in
        *.html.gz) echo "text/html" ;;
        *.js.gz)   echo "application/javascript" ;;
        *.css.gz)  echo "text/css" ;;
        *.json.gz) echo "application/json" ;;
        *.webmanifest.gz) echo "application/manifest+json" ;;
        *.svg.gz)  echo "image/svg+xml" ;;
        *.png)     echo "image/png" ;;
        *.ico)     echo "image/x-icon" ;;
        *)         echo "application/octet-stream" ;;
    esac
}

# Process all files
while IFS= read -r -d '' filepath; do
    # Get path relative to WEB_DIR
    relpath="${filepath#$WEB_DIR}"

    # URI is the path without .gz extension
    if [[ "$relpath" == *.gz ]]; then
        uri="${relpath%.gz}"
        gzipped="true"
    else
        uri="$relpath"
        gzipped="false"
    fi

    # Generate C symbol name
    symbol=$(generate_symbol "${relpath#/}")
    content_type=$(get_content_type "$relpath")

    # CMake embed path (relative to esp32/)
    cmake_path="web${relpath}"
    EMBED_FILES="$EMBED_FILES \"${cmake_path}\""

    # C declarations
    ENTRIES="${ENTRIES}
extern const uint8_t web_${symbol}_start[] asm(\"_binary_${symbol}_start\");
extern const uint8_t web_${symbol}_end[] asm(\"_binary_${symbol}_end\");"

    # Table entry
    ENTRIES="${ENTRIES}
// ${uri} -> ${relpath}"

    INDEX=$((INDEX + 1))
done < <(find "$WEB_DIR" -type f -print0 | sort -z)

# Build the file table entries separately
TABLE_ENTRIES=""
while IFS= read -r -d '' filepath; do
    relpath="${filepath#$WEB_DIR}"
    if [[ "$relpath" == *.gz ]]; then
        uri="${relpath%.gz}"
        gzipped="true"
    else
        uri="$relpath"
        gzipped="false"
    fi
    symbol=$(generate_symbol "${relpath#/}")
    content_type=$(get_content_type "$relpath")

    TABLE_ENTRIES="${TABLE_ENTRIES}
    { \"${uri}\", web_${symbol}_start, 0, \"${content_type}\", ${gzipped} },"
done < <(find "$WEB_DIR" -type f -print0 | sort -z)

# Write the generated header
cat > "$GEN_HEADER" << HEADER_EOF
#pragma once
// Auto-generated by prepare_web.sh — do not edit manually.

#include "web_files.h"

HEADER_EOF

# Add extern declarations
while IFS= read -r -d '' filepath; do
    relpath="${filepath#$WEB_DIR}"
    symbol=$(generate_symbol "${relpath#/}")
    cat >> "$GEN_HEADER" << DECL_EOF
extern const uint8_t web_${symbol}_start[] asm("_binary_${symbol}_start");
extern const uint8_t web_${symbol}_end[] asm("_binary_${symbol}_end");
DECL_EOF
done < <(find "$WEB_DIR" -type f -print0 | sort -z)

# Add the file count define and table
FILE_COUNT=$(find "$WEB_DIR" -type f | wc -l | tr -d ' ')

cat >> "$GEN_HEADER" << TABLE_START_EOF

#define WEB_FILE_COUNT ${FILE_COUNT}

static const WebFile web_files[] = {
TABLE_START_EOF

while IFS= read -r -d '' filepath; do
    relpath="${filepath#$WEB_DIR}"
    if [[ "$relpath" == *.gz ]]; then
        uri="${relpath%.gz}"
        gzipped="true"
    else
        uri="$relpath"
        gzipped="false"
    fi
    symbol=$(generate_symbol "${relpath#/}")
    content_type=$(get_content_type "$relpath")

    echo "    { \"${uri}\", web_${symbol}_start, static_cast<size_t>(web_${symbol}_end - web_${symbol}_start), \"${content_type}\", ${gzipped} }," >> "$GEN_HEADER"
done < <(find "$WEB_DIR" -type f -print0 | sort -z)

cat >> "$GEN_HEADER" << TABLE_END_EOF
};

static const int web_file_count = WEB_FILE_COUNT;
TABLE_END_EOF

echo "Generated $GEN_HEADER ($FILE_COUNT files)"

# Write CMake embed file
echo "# Auto-generated by prepare_web.sh — do not edit manually." > "$GEN_CMAKE"
echo "set(WEB_EMBED_FILES" >> "$GEN_CMAKE"
while IFS= read -r -d '' filepath; do
    relpath="${filepath#$WEB_DIR}"
    echo "    \"\${CMAKE_CURRENT_SOURCE_DIR}/../web${relpath}\"" >> "$GEN_CMAKE"
done < <(find "$WEB_DIR" -type f -print0 | sort -z)
echo ")" >> "$GEN_CMAKE"

echo "Generated $GEN_CMAKE"
echo "Done! Run 'idf.py build' to compile firmware with embedded web files."
